# Generated by Django 5.1.1 on 2024-10-03 06:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name='Fecha de Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='comisiones.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(default='', max_length=10, verbose_name='Numero de Pedido')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de comision')),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad de Comision')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='comisiones.empleado')),
            ],
        ),
    ]
