services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: SICOCO
    #restart: always
    ports:
      - 8000:8000
    command: python3 manage.py runserver 0:8000
    
    volumes:
      - .:/SICOCO
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: